### PR TITLE
Stateful widget state losing issue fix.

### PR DESCRIPTION
**Pull request by Ninja260**

### CODE REVIEW

**Comment by Ninja260** [comment]
Hello bro @rayliverified, I am waiting follow up from you for my pull request. 
I am having state losing issue because of layout change while I am using the library. This is why this pull request happens. I will be waiting for you reply.

**Comment by rayliverified** [comment]
I don't understand what Flex solves here. Can you help me understand?

**Comment by Ninja260** [comment]
If we put a StatefulWidget under a ResponsiveRowColumn widget, the stateful widget loses state  when the ResponsiveRowColumn layout change from Row to Column, and vice versa. This is because the inner widget tree of the ResponsiveRowColumn changes when Row or Column is being conditionally rendered.

To Solve this issue, I proposed to use Flex in place of using Row and Column. Flex have the same constructor arguments as Row or Column. The only difference is that we need to define the direction argument, which is used to decide whether to render as Row or Column. 

In that way, the inner widget tree of the ResponsiveRowColumn will remain intact even the layout changes. The state losing issue is prevented.

**Comment by Ninja260** [comment]
bro @rayliverified . I am waiting response from you. :)

**Pull request merged**
